server:
  port: 30300

spring:
  application:
    name: generator-init

  cloud:
    stream:
      bindings:
        patient-create:
          destination: patient-create-requests
        doctor-create:
          destination: doctor-create-requests
        clinic-create:
          destination: clinic-create-requests

producer:
  doctor-count: 1000
  patient-count: 1000
  clinic-count: 1000
